"""add user preferences

Revision ID: 1c1c21ea481b
Revises: 3a60b9637be5
Create Date: 2026-03-21 14:21:56.602556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c1c21ea481b'
down_revision: Union[str, Sequence[str], None] = '3a60b9637be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planner_id'), 'planner', ['id'], unique=False)
    op.drop_index('ix_search_history_id', table_name='search_history')
    op.drop_index('ix_search_history_user_id', table_name='search_history')
    op.drop_table('search_history')
    op.add_column('saved_events', sa.Column('planner_id', sa.Integer(), nullable=True))
    op.add_column('saved_events', sa.Column('title', sa.String(), nullable=False))
    op.add_column('saved_events', sa.Column('date', sa.String(), nullable=False))
    op.add_column('saved_events', sa.Column('time', sa.String(), nullable=False))
    op.add_column('saved_events', sa.Column('tag', sa.String(), nullable=False))
    op.add_column('saved_events', sa.Column('price', sa.String(), nullable=False))
    op.alter_column('saved_events', 'saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_saved_events_user_id', table_name='saved_events')
    op.create_foreign_key(None, 'saved_events', 'planner', ['planner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('saved_events', 'duration_minutes')
    op.drop_column('saved_events', 'description')
    op.drop_column('saved_events', 'category')
    op.drop_column('saved_events', 'event_url')
    op.drop_column('saved_events', 'start_time')
    op.drop_column('saved_events', 'name')
    op.drop_column('saved_events', 'source')
    op.drop_column('saved_events', 'indoor')
    op.drop_column('saved_events', 'estimated_cost')
    op.drop_column('saved_events', 'end_time')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.String(), nullable=True))
    op.add_column('users', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'budget')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'preference')
    op.drop_column('users', 'name')
    op.drop_column('users', 'username')
    op.add_column('saved_events', sa.Column('end_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('saved_events', sa.Column('estimated_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('saved_events', sa.Column('indoor', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('saved_events', sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('saved_events', sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('saved_events', sa.Column('start_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('saved_events', sa.Column('event_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('saved_events', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('saved_events', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('saved_events', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'saved_events', type_='foreignkey')
    op.create_index('ix_saved_events_user_id', 'saved_events', ['user_id'], unique=False)
    op.alter_column('saved_events', 'saved_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('saved_events', 'price')
    op.drop_column('saved_events', 'tag')
    op.drop_column('saved_events', 'time')
    op.drop_column('saved_events', 'date')
    op.drop_column('saved_events', 'title')
    op.drop_column('saved_events', 'planner_id')
    op.create_table('search_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('interests', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='search_history_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='search_history_pkey')
    )
    op.create_index('ix_search_history_user_id', 'search_history', ['user_id'], unique=False)
    op.create_index('ix_search_history_id', 'search_history', ['id'], unique=False)
    op.drop_index(op.f('ix_planner_id'), table_name='planner')
    op.drop_table('planner')
    # ### end Alembic commands ###
