"""add_preferences_to_users

Revision ID: ac69a6239172
Revises: 1c1c21ea481b
Create Date: 2026-03-22 20:47:35.771443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac69a6239172'
down_revision: Union[str, Sequence[str], None] = '1c1c21ea481b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.drop_column('users', 'interests')
    op.drop_column('users', 'budget')
    op.drop_column('users', 'preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('budget', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('interests', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###
